Remove reflection and boxed math operations #37
fulcrologic/guardrails pull request #38
Opened 2024-02-13 18:37 UTC by FieryCod

2024-02-13 20:26 UTC, awkay requested changes

2024-02-13 20:26 UTC, awkay commented on src/main/com/fulcrologic/guardrails/config.cljc
> +#?(:clj
I do not want to propagate this to every user.

2024-02-13 20:26 UTC, awkay commented on src/main/com/fulcrologic/guardrails/core.cljc
> +#?(:clj
Again, this cannot be left here.

2024-02-13 20:26 UTC, awkay commented on src/main/com/fulcrologic/guardrails/impl/externs.cljc
> +#?(:clj
another one

2024-02-13 20:26 UTC, awkay commented on src/main/com/fulcrologic/guardrails/impl/pro.cljc
> +#?(:clj
ditto

2024-02-13 20:26 UTC, awkay commented on src/main/com/fulcrologic/guardrails/malli/core.cljc
> +#?(:clj
ditto

2024-02-13 20:26 UTC, awkay commented on src/main/com/fulcrologic/guardrails/malli/registry.cljc
> +     (set! *unchecked-math* :warn-on-boxed)))
ditto

2024-02-13 20:26 UTC, awkay commented on src/main/com/fulcrologic/guardrails/utils.cljc
> +#?(:clj
ditto

2024-02-13 20:26 UTC, awkay commented on src/main/com/fulcrologic/guardrails/utils.cljc
> +    (let [^"[Ljava.lang.Object;" backtrace *backtrace*
inconsistent use of hint-backtrace.

2024-02-16 06:07 UTC, FieryCod commented
@awkay thank you for all the comments. It's ready to be merged! now.

2024-02-16 07:55 UTC, awkay approved these changes

2024-02-16 07:55 UTC, merged

2024-02-16 07:55 UTC, awkay commented
Thanks